language: go
go:
  - 1.8.3
install:
  - go get github.com/constabulary/gb/...
script:
  - gb build
  - gb vendor restore
  - gb test -v
notifications:
  recipients:
    - baxzzzz@gmail.com
  email:
    on_success: change
    on_failure: always
