language: go
go:
  - 1.8.3

install:
  - go get github.com/golang/mock/gomock
  - go get github.com/mitchellh/mapstructure
  - go get gopkg.in/mgo.v2

script:
  - go test -v ./...

notifications:
  recipients:
    - baxzzzz@gmail.com
  email:
    on_success: change
    on_failure: always
