// Code generated by MockGen. DO NOT EDIT.
// Source: geoip/provider.go

// Package geoip is a generated GoMock package.
package geoip

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockProvider is a mock of Provider interface
type MockProvider struct {
	ctrl     *gomock.Controller
	recorder *MockProviderMockRecorder
}

// MockProviderMockRecorder is the mock recorder for MockProvider
type MockProviderMockRecorder struct {
	mock *MockProvider
}

// NewMockProvider creates a new mock instance
func NewMockProvider(ctrl *gomock.Controller) *MockProvider {
	mock := &MockProvider{ctrl: ctrl}
	mock.recorder = &MockProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockProvider) EXPECT() *MockProviderMockRecorder {
	return m.recorder
}

// GetIPInfo mocks base method
func (m *MockProvider) GetIPInfo(ipAddress string) (*IPInfo, error) {
	ret := m.ctrl.Call(m, "GetIPInfo", ipAddress)
	ret0, _ := ret[0].(*IPInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIPInfo indicates an expected call of GetIPInfo
func (mr *MockProviderMockRecorder) GetIPInfo(ipAddress interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIPInfo", reflect.TypeOf((*MockProvider)(nil).GetIPInfo), ipAddress)
}
